# builds approved AI input payloads.
from typing import Any

from rolling.app.models.analyses import AnalysisResultResponse, AnalysisReportResponse
from rolling.app.models.ai import AIAnalysisReportInput


class AIInputBuilder:
    """
    A class that constructs input for the AI service.

    All inputs need to be whitelisted. It takes analysis results generated by the analysis engine and extracts the
    whitelisted keys.

    Attributes
    ----------
        ALLOWED_NAME_TABLES (set[str]): A set of table names that the AI service is allowed to access.
        ALLOWED_KEYS (set[str]): A set of keys in the analysis results that the AI service is allowed to access.
    """
    ALLOWED_TABLE_NAMES = {"hormone_statistics",
                           "hormone_performance_statistics",
                           "hormone_phase_statistics",
                           "hormone_dysmenorrhea_statistics",
                           "hormone_dysmenorrhea_performance_statistics",
                           "hormone_dysmenorrhea_phase_statistics",
                           "hormone_performance_phase_statistics",
                           "comparative_hormone_phase_statistics",
                           "comparative_hormone_performance_statistics",
                           "comparative_hormone_dysmenorrhea_statistics",
                           "comparative_hormone_dysmenorrhea_performance_statistics",
                           "comparative_hormone_dysmenorrhea_phase_statistics",
                           "comparative_hormone_performance_phase_statistics"}
    
    ALLOWED_KEYS = {"hormone_name",
                    "dysmenorrhea_present",
                    "performance_type",
                    "dysmenorrhea_present_a",
                    "dysmenorrhea_present_b",
                    "performance_type_a",
                    "performance_type_b",
                    "observation_count",
                    "obervation_count_a",
                    "observation_count_b",
                    "mean",
                    "mean_a",
                    "mean_b",
                    "median",
                    "median_a",
                    "median_b",
                    "standard_deviation",
                    "standard_deviation_a",
                    "standard_deviation_b",
                    "hedges_g",
                    "independent_t"}
    
    def build_allowed_ai_input(self,
                               analysis_results: list[AnalysisResultResponse],
                               analysis_report: AnalysisReportResponse,
                               ) -> AIAnalysisReportInput:
        """
        Constructs the AI input allowed for an AI service.

        Args:
            analysis_results (list[AnalysisResultResponse]): List of analysis results generated by the analysis engine.
            analysis_report (AnalysisReportResponse): A traditionally constructed analysis report generated by the analysis engine.

        Returns:
            AIAnalysisReportInput: a structured object for the input to the AI service.
        """
        combined_summaries = []
        combined_tables = []

        for analysis_result in analysis_results:
            result_payload = analysis_result.result_payload

            summary = result_payload.get("summary", {})
            tables = result_payload.get("tables", [])
            approved_tables = self.extract_approved_tables(tables=tables,
                                                           analysis_result=analysis_result)
            redacted_tables = self.get_whitelisted_keys_from_tables(approved_tables)

            combined_summaries.append({"analysis_result_id": str(analysis_result.analysis_result_id),
                                       "analysis_run_id": str(analysis_result.analysis_run_id),
                                       "result_type": analysis_result.result_type,
                                       "summary": summary})
            
            combined_tables = [*combined_tables, *redacted_tables]
            
        metadata = {"analysis_run_id": str(analysis_report.analysis_run_id),
                    "source_result_ids": [str(result.analysis_result_id) for result in analysis_results],
                    "result_types": [result.result_type for result in analysis_results],
                    "table_names": [table["name"] for table in combined_tables]}
    
        return AIAnalysisReportInput(summary={"results": combined_summaries},
                             tables=combined_tables,
                             report_text=analysis_report.report_text,
                             summary_text=analysis_report.summary_text,
                             metadata=metadata)

    # HELPERS
    def extract_approved_tables(self,
                                tables: list[dict[str, Any]],
                                analysis_result: AnalysisResultResponse
                                ) -> list[dict[str, Any]]:
        """
        Extracts the approved tables from an analysis result.

        Only extracts tables listed in attribute ALLOWED_TABLE_NAMES.

        Args:
            tables (list[dict[str, Any]]): List of tables generated by the analysis engine.
            analysis_result (AnalysisResultResponse): Analysis result generated by the analysis engine.

        Returns:
            list[dict[str, Any]]: A list of approved tables with their content.
        """
        approved_tables = []
        for table in tables:
            table_name = table.get("name")
            table_rows = table.get("rows", [])

            if table_name not in self.ALLOWED_TABLE_NAMES:
                continue

            approved_tables.append({"name": table_name,
                                    "rows": table_rows,
                                    "source_analysis_result_id": str(analysis_result.analysis_result_id),
                                    "source_result_type": analysis_result.result_type})
            
        return approved_tables
    
    def get_whitelisted_keys_from_tables(self, tables: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """
        Gets only whitelisted keys from a list of tables.

        Only extracts the keys list in attribute ALLOWED_KEYS.

        Args:
            tables (list[dict[str, Any]]): List of tables generated by the analysis engine.

        Returns:
            list[dict[str, Any]]: A list of tables with the whitelisted keys.
        """
        redacted_tables = []
        for table in tables:
            table_name = table.get("name")
            table_rows = table.get("rows", [])

            redacted_rows = []
            for row in table_rows:
                row = dict()
                for key, value in row.items():
                    if key in self.ALLOWED_KEYS:
                        row[key] = value
                redacted_rows.append(row)

            redacted_tables.append({"name": table_name,
                                    "rows": redacted_rows})
        return redacted_tables
