CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- Drops if they exist
DROP TABLE IF EXISTS research.analysts CASCADE;
DROP TABLE IF EXISTS research.athletes CASCADE;
DROP TABLE IF EXISTS research.datasets CASCADE;
DROP TABLE IF EXISTS research.performance_records CASCADE;
DROP TABLE IF EXISTS research.hormone_measurements CASCADE;
DROP TABLE IF EXISTS research.cycle_phase_records CASCADE;
DROP TABLE IF EXISTS research.symptom_records CASCADE;

-- TABLE CREATION
-- USER PROFILE
CREATE TABLE research.analysts (
    -- analyst profile (assuming it will be very small since local)
    analyst_id      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username        TEXT NOT NULL UNIQUE,
    email           TEXT NOT NULL UNIQUE,
    pswd_hash       TEXT NOT NULL,
    pswd_salt       TEXT NOT NULL,
    pswd_date       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- SUBJECT AND METADATA
CREATE TABLE research.athletes (
    -- might be useful for mapping across different datasets with differing IDs
    athlete_id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_code       TEXT NOT NULL, -- TODO: define required format for this code
    dataset_id          UUID references research.datasets(dataset_id) on delete cascade,
    birth_date          DATE,
    birth_year          INTEGER,
    age_at_observation  SMALLINT, -- if birth_date not available; trigger updated after a year
    age_logged_at       TIMESTAMPTZ DEFAULT NOW(),
    notes               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (
        external_code ~ '^R[0-9]{1}[A-Z0-9]{3}$'
    ),
    CHECK (
        birth_date IS NOT NULL
        OR birth_year IS NOT NULL
        OR age_at_observation IS NOT NULL
    ),
    CHECK ( -- avoids contradictory inputs
    birth_date IS NULL
    OR birth_year IS NULL
    OR EXTRACT(YEAR FROM birth_date) = birth_year
)
);

CREATE TABLE research.datasets (
    -- linking table pointing to different kinds of datasets
    dataset_id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    uploaded_by_id      UUID NOT NULL REFERENCES research.analysts(analyst_id) ON DELETE RESTRICT,
    original_file_name  TEXT NOT NULL,
    stored_relative_path TEXT NOT NULL,
    content_hash        TEXT,
    uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    import_status       TEXT NOT NULL DEFAULT 'uploaded',
    notes               TEXT
);

-- LOOKUP TABLES
-- Performances
CREATE TABLE research.performance_metric_types (
    metric_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    unit            TEXT
);
-- TODO: insert here

CREATE TABLE research.performance_types (
    performance_type_id    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name                   VARCHAR(100) NOT NULL UNIQUE
); -- TODO: add specific ones here

-- Menstruation
CREATE TABLE research.cycle_phase_types (
    cycle_phase_type_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    TEXT NOT NULL UNIQUE
);

CREATE TABLE research.menstrual_symptoms (
    menstrual_symptom_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100) NOT NULL UNIQUE
);
-- TODO: add symptoms

CREATE TABLE research.symptom_severity (
    symptom_severity 	TEXT PRIMARY KEY DEFAULT 'MILD',
    CONSTRAINT  severity_allowed_chk CHECK (symptom_severity IN ('MILD', 'MODERATE', 'SEVERE'))
);

-- Physiological
CREATE TABLE research.sexes (
    sex CHAR(1) PRIMARY KEY,
    CONSTRAINT sexes_allowed_chk CHECK (sex IN ('F', 'M', 'I'))
);
-- Hormones
CREATE TABLE research.relations (
    relation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL UNIQUE
);

CREATE TABLE research.glands (
    name        TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE research.chemical_classes (
    name                TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE research.hormones (
    hormone_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL,
    gland               TEXT REFERENCES research.glands(name) ON DELETE RESTRICT ON UPDATE CASCADE,
    chemical_class      TEXT REFERENCES research.chemical_classes(name) ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE(name, gland, chemical_class)
);

CREATE TABLE research.hormone_relations (
    source_hormone TEXT NOT NULL
        REFERENCES research.hormones(hormone_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    target_hormone TEXT NOT NULL
        REFERENCES research.hormones(hormone_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    relation TEXT NOT NULL
        REFERENCES research.relations(name)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    notes TEXT,
    PRIMARY KEY (source_hormone, target_hormone, relation),
    CHECK (source_hormone <> target_hormone)
);
-- TODO: write script for populating hormones (and generally, look-up tables)

-- DOMAIN DATA
CREATE TABLE research.performance_records (
    -- typical performance record
    performance_record_id    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    athlete_id               UUID NOT NULL,
    dataset_id               UUID REFERENCES research.datasets(dataset_id) ON DELETE CASCADE,
    performance_type         UUID NOT NULL,
    metric_type              BIGINT NOT NULL REFERENCES research.performance_metric_types(metric_type_id) ON DELETE RESTRICT,
    metric_value             NUMERIC NOT NULL,
    metric_unit              TEXT,
    observed_on              DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT performance_athlete_fk
        FOREIGN KEY (athlete_id)
        REFERENCES research.athletes (athlete_id)
        ON DELETE CASCADE,
    CONSTRAINT performance_type_fk
        FOREIGN KEY (performance_type)
        REFERENCES research.performance_types (performance_type_id)
        ON DELETE RESTRICT
);

CREATE TABLE research.hormone_measurements (
    -- timeseries hormone measurement
    hormone_measurement_id  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    athlete_id              UUID NOT NULL REFERENCES research.athletes(athlete_id) ON DELETE CASCADE,
    hormone_id              BIGINT NOT NULL REFERENCES research.hormones(hormone_id) ON DELETE RESTRICT,
    dataset_id              UUID REFERENCES research.datasets(dataset_id) ON DELETE CASCADE,
    measured_value          NUMERIC,
    unit                    TEXT, -- TODO: application level will fill this
    observed_on             DATE DEFAULT CURRENT_DATE,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE research.cycle_phase_records (
    -- timeseries menstrual cycle records
    cycle_phase_record_id   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    athlete_id              UUID NOT NULL REFERENCES research.athletes(athlete_id) ON DELETE CASCADE,
    dataset_id              UUID REFERENCES research.datasets(dataset_id) ON DELETE CASCADE,
    observed_on             DATE NOT NULL,
    cycle_phase_type        BIGINT NOT NULL REFERENCES research.cycle_phase_types(cycle_phase_type_id) ON DELETE RESTRICT,
    cycle_day               INTEGER,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE research.symptom_records (
    -- timeseries menstrual symptom records
    symptom_record_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    athlete_id              UUID NOT NULL REFERENCES research.athletes(athlete_id) ON DELETE CASCADE,
    dataset_id              UUID REFERENCES research.datasets(dataset_id) ON DELETE CASCADE,
    symptom_id              BIGINT REFERENCES research.menstrual_symptoms(menstrual_symptom_id) ON DELETE RESTRICT,
    observed_on             DATE NOT NULL,
    symptom_severity        TEXT REFERENCES research.symptom_severity(symptom_severity) ON DELETE RESTRICT ON UPDATE CASCADE,
    relative_day_to_cycle   BIGINT,
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE research.athlete_body (
    athlete_id      UUID PRIMARY KEY,
    mass            REAL NOT NULL CHECK (mass > 0),
    height          REAL NOT NULL CHECK (height > 0),
    sex             CHAR(1) NOT NULL,
    transitioning   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT body_athlete_fk
        FOREIGN KEY (athlete_id)
        REFERENCES research.athletes (athlete_id)
        ON DELETE CASCADE,
    CONSTRAINT body_sex_fk
        FOREIGN KEY (sex)
        REFERENCES research.sexes (sex)
        ON DELETE RESTRICT
);



-- FUNCTIONS
-- DOMAIN
CREATE OR REPLACE FUNCTION research.get_age(
    -- Sets precedence: birth_date > birth_year > age
    p_birth_date DATE,
    p_birth_year INTEGER,
    p_age INTEGER,
    p_reference_date DATE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_birth_date IS NOT NULL THEN
        RETURN EXTRACT(YEAR FROM AGE(p_reference_date, p_birth_date));
    ELSIF p_birth_year IS NOT NULL THEN
        RETURN EXTRACT(YEAR FROM p_reference_date) - p_birth_year;
    ELSE
        RETURN p_age;
    END IF;
END;
$$;
